<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>MyApp.Namespace</RootNamespace>
    <Nullable>warnings</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EPiServer.CMS" Version="13.0.0-preview2-pre-35" />
    <PackageReference Include="EPiServer.Cms.UI.AspNetIdentity" Version="13.0.0-preview2-pre-35" />
  </ItemGroup>
</Project>
