<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="EPiServer"/>
    <Using Include="EPiServer.Core"/>
    <Using Include="EPiServer.DataAbstraction"/>
    <Using Include="EPiServer.DataAnnotations"/>
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="EPiServer.CMS" Version="13.0.0-preview2-pre-35" />
    <PackageReference Include="EPiServer.Cms.UI.AspNetIdentity" Version="13.0.0-preview2-pre-35" />
  </ItemGroup>
  
  <ItemGroup>
    <EmbeddedResource Include="Resources\Translations\**\*" />
  </ItemGroup>
</Project>
